version: '2'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    container_name: maktaba_drupal
    entrypoint: ./drupal-entrypoint.sh
    command: [apache2-foreground]
    networks:
      - private-network

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/exports:/docker-entrypoint-initdb.d
    networks:
      - private-network

  elastic-search:
    image: elasticsearch:5.2.0-alpine
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
